### PR TITLE
Turned the main image into a gallery of images. Added an icon.

### PR DESCRIPTION
**Pull request by matthieudelaro**
Merged some stuff from the website I created yesterday

### CODE REVIEW

**Comment by brouberol** [comment]
As there is no way to preview this, I'm gonna accept this.

**Comment by t0b1nux** [comment]
This is something lacking in github pages, among others. If you're working at OVH, you should find this very frustrating ...

**Comment by brouberol** [comment]
Is the github-page website re-generated automatically everytime a commit hits the ``gh-page`` branch?

**Comment by t0b1nux** [comment]
Yes, it should be

**Comment by brouberol** [comment]
Ok, let's wait then.

**Comment by t0b1nux** [comment]
The ability to test before pushing without doing it manually would still be great. It's pretty basic but not integrated.. Somedays GitHub have very strange strategies

**Comment by t0b1nux** [comment]
Yeah, it works

**Pull request merged**
