### PR TITLE
Add CNAME

### PR DESCRIPTION
**Pull request by t0b1nux**
add cname file so that dns will work (currently works with marcel.simonthoby.tk, need to gain access to chauffemarcel.tk to utilise it as well)

### CODE REVIEW

**Comment by brouberol** [comment]
Could you squash both commits? I'll merge it right after.

**Comment by brouberol** [comment]
Btw, how does this work?

**Comment by t0b1nux** [comment]
I adde an cname in my dns record (marcel		IN	CNAME	brouberol.github.io), and this tells github this is the right folder and branch to look at

**Comment by t0b1nux** [comment]
Sorry, I'm not a git expert but it's now ok,  I think

**Comment by brouberol** [comment]
I received the following image right after the merge:

The page build completed successfully, but returned the following warning:

CNAME already taken: marcel.simonthoby.tk. Check out https://help.github.com/articles/my-custom-domain-isn-t-working/#cname-already-taken for more information.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.

**Comment by t0b1nux** [comment]
I will release it now on my own branch

**Comment by t0b1nux** [comment]
Should be ok now

**Comment by t0b1nux** [comment]
Wait, I don't get it, It no longer works !
I will lread github doc again...

**Comment by t0b1nux** [comment]
Could you see if the cname is still taken ?

**Comment by t0b1nux** [comment]
I know ! 
"To use your custom domain, whether you're setting up an apex domain or a subdomain, you need to remove the CNAME file from the other repository in which it's used." -> I've done that
" After you have done this, you will also need to push again to trigger a new page build." -> I couldn't do this but you can

**Pull request merged**
